In [81]:
! pip install psycopg2

Collecting psycopg2
  Using cached psycopg2-2.9.6-cp310-cp310-win_amd64.whl (1.2 MB)
Installing collected packages: psycopg2

ERROR: Could not install packages due to an OSError: [WinError 5] Access is denied: 'c:\\Users\\eduar\\Documents\\NoSQL_Lab_and_MongoDB\\nosql_lab\\venv\\Lib\\site-packages\\psycopg2\\_psycopg.cp310-win_amd64.pyd'
Check the permissions.

In [84]:
import datetime
import time
import logging
import json
import os
import psycopg2
import pandas as pd
import requests
import numpy as np

#from airflow import DAG
#from airflow.operators.python_operator import PythonOperator
#from airflow.operators.postgres_operator import PostgresOperator
#from airflow.hooks.postgres_hook import PostgresHook
#from airflow.timetables.trigger import CronTriggerTimetable

# Database credentials
ENDPOINT = 'sharedmobility.cnls2nxrzngg.us-east-1.rds.amazonaws.com'   #Nithu's shared point
DB_NAME = 'sharedmobility'
USERNAME = 'nithu'
PASSWORD = 'DWH_2023'


# Connect to the database
try:
    print("host={} dbname={} user={} password={}".format(ENDPOINT, DB_NAME, USERNAME, PASSWORD))
    conn = psycopg2.connect("host={} dbname={} user={} password={}".format(ENDPOINT, DB_NAME, USERNAME, PASSWORD))

except psycopg2.Error as e:
    print("Error: Could not make connection to the Postgres database")
    print(e)


# Get cursor to the database    
try:    
    cur = conn.cursor()

except psycopg2.Error as e:
    print("Error: Could not get curser to the Database")
    print(e)

# Auto commit to the database
conn.set_session(autocommit=True)

# Fetch table from database
try:
    data = pd.read_sql('SELECT * FROM statusdb', conn)    
    #cur.execute("SELECT * FROM statusdb")
except psycopg2.Error as e:
    print("Error: Could not get data from the database")
    print(e)




data.head()

host=sharedmobility.cnls2nxrzngg.us-east-1.rds.amazonaws.com dbname=sharedmobility user=nithu password=DWH_2023

C:\Users\eduar\AppData\Local\Temp\ipykernel_23236\787720625.py:47: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  data = pd.read_sql('SELECT * FROM statusdb', conn)

,load,station_id,is_installed,is_renting,is_returning,last_reported,num_bikes_available,num_docks_available,provider_id
0,2023-04-19 14:21:41.445570,emobility:69636,true,true,true,1681913867,0,0,emobility
1,2023-04-19 14:21:41.445570,emobility:69644,true,true,true,1681913867,3,0,emobility
2,2023-04-19 14:21:41.445570,emobility:69652,true,true,true,1681913867,1,0,emobility
3,2023-04-19 14:21:41.445570,emobility:69677,true,true,true,1681913867,2,0,emobility
4,2023-04-19 14:21:41.445570,emobility:69682,true,true,true,1681913867,1,0,emobility

In [85]:
# create a new column with the difference between the current num_bikes_available and the previous one

data = data.sort_values(by=['station_id', 'load'])
data['usage'] = data['num_bikes_available'].diff()
data[data['station_id'] == 'emobility:69636']

,load,station_id,is_installed,is_renting,is_returning,last_reported,num_bikes_available,num_docks_available,provider_id,usage
0,2023-04-19 14:21:41.445570,emobility:69636,true,true,true,1681913867,0,0,emobility,-1.0
6111,2023-04-19 19:09:32.167965,emobility:69636,true,true,true,1681931179,2,0,emobility,2.0
8657,2023-04-20 09:24:48.047367,emobility:69636,true,true,true,1681982460,2,0,emobility,0.0
14718,2023-04-20 10:58:48.597871,emobility:69636,true,true,true,1681988049,1,0,emobility,-1.0
20818,2023-04-20 12:13:30.749037,emobility:69636,true,true,true,1681992617,2,0,emobility,1.0
26919,2023-04-20 13:27:58.952975,emobility:69636,true,true,true,1681997197,2,0,emobility,0.0
32712,2023-04-20 17:27:40.697754,emobility:69636,true,true,true,1682011614,0,0,emobility,-2.0
35297,2023-04-20 17:48:41.533427,emobility:69636,true,true,true,1682012595,0,0,emobility,0.0
42369,2023-04-21 06:10:26.457343,emobility:69636,true,true,true,1682057263,2,0,emobility,2.0
42370,2023-04-21 08:35:26.773685,emobility:69636,true,true,true,1682065775,2,0,emobility,0.0
48497,2023-04-21 09:12:49.563324,emobility:69636,true,true,true,1682068052,1,0,emobility,-1.0
54526,2023-04-21 10:38:58.442079,emobility:69636,true,true,true,1682073265,2,0,emobility,1.0
60652,2023-04-21 11:31:54.043128,emobility:69636,true,true,true,1682076527,2,0,emobility,0.0
66726,2023-04-21 12:09:40.481938,emobility:69636,true,true,true,1682078812,1,0,emobility,-1.0
72852,2023-04-21 13:17:56.915120,emobility:69636,true,true,true,1682082730,1,0,emobility,0.0
78978,2023-04-21 18:33:06.638373,emobility:69636,true,true,true,1682101970,1,0,emobility,0.0
85030,2023-04-22 09:00:03.002165,emobility:69636,true,true,true,1682153801,1,0,emobility,0.0
91161,2023-04-22 09:15:35.518340,emobility:69636,true,true,true,1682154777,1,0,emobility,0.0
97289,2023-04-22 09:46:14.932832,emobility:69636,true,true,true,1682156410,1,0,emobility,0.0
103420,2023-04-22 11:14:29.529747,emobility:69636,true,true,true,1682161957,1,0,emobility,0.0
109424,2023-04-22 11:48:56.172212,emobility:69636,true,true,true,1682163915,0,0,emobility,-1.0
115546,2023-04-22 12:22:59.355595,emobility:69636,true,true,true,1682165871,0,0,emobility,0.0
121669,2023-04-22 12:56:53.333417,emobility:69636,true,true,true,1682168152,1,0,emobility,1.0
127791,2023-04-22 13:30:56.516879,emobility:69636,true,true,true,1682170106,1,0,emobility,0.0
129265,2023-04-22 14:12:21.960643,emobility:69636,true,true,true,1682172395,0,0,emobility,-1.0
135230,2023-04-22 14:45:02.352671,emobility:69636,true,true,true,1682174363,0,0,emobility,0.0
141360,2023-04-22 15:27:15.208209,emobility:69636,true,true,true,1682176967,0,0,emobility,0.0
147491,2023-04-22 15:57:23.152034,emobility:69636,true,true,true,1682178926,0,0,emobility,0.0
153620,2023-04-22 17:15:46.375886,emobility:69636,true,true,true,1682183518,0,0,emobility,0.0
159751,2023-04-23 08:21:41.872378,emobility:69636,true,true,true,1682238024,1,0,emobility,1.0
165730,2023-04-23 09:29:35.465136,emobility:69636,true,true,true,1682241945,1,0,emobility,0.0
171861,2023-04-23 10:15:29.551326,emobility:69636,true,true,true,1682244885,1,0,emobility,0.0
177990,2023-04-23 12:34:13.682465,emobility:69636,true,true,true,1682253056,0,0,emobility,-1.0
184122,2023-04-23 14:57:02.414928,emobility:69636,true,true,true,1682261553,0,0,emobility,0.0
189202,2023-04-24 07:41:40.360283,emobility:69636,true,true,true,1682321977,0,0,emobility,0.0
195338,2023-04-24 08:28:13.740516,emobility:69636,true,true,true,1682324576,1,0,emobility,1.0
201475,2023-04-24 08:59:03.478652,emobility:69636,true,true,true,1682326529,2,0,emobility,1.0
207301,2023-04-24 14:30:32.975098,emobility:69636,true,true,true,1682346518,2,0,emobility,0.0
210801,2023-04-25 17:35:52.924968,emobility:69636,true,true,true,1682444011,2,0,emobility,0.0
216901,2023-04-25 18:23:29.045513,emobility:69636,true,true,true,1682446940,2,0,emobility,0.0
223001,2023-04-25 18:54:24.756996,emobility:69636,true,true,true,1682448571,2,0,emobility,0.0
229101,2023-04-25 19:11:58.139962,emobility:69636,true,true,true,1682449878,2,0,emobility,0.0

In [78]:
# create a new column called 'usage' with the difference between the current num_bikes_available and the previous one
data['usage'] = data.groupby(['station_id'])['num_bikes_available'].diff()*(-1)
columns_list = ['load','station_id', 'num_bikes_available', 'usage']
# Set negative values to 0
data['usage'] = data['usage'].apply(lambda x: max(0, x))
usage_df = data[columns_list]
# Check one single station_id
usage_df[usage_df['station_id'] == 'emobility:69636']

                           load       station_id  num_bikes_available  usage
0       2023-04-19 14:21:41.445  emobility:69636                    0    0.0
6111    2023-04-19 19:09:32.167  emobility:69636                    2    0.0
8657    2023-04-20 09:24:48.047  emobility:69636                    2    0.0
14718   2023-04-20 10:58:48.597  emobility:69636                    1    1.0
20818   2023-04-20 12:13:30.749  emobility:69636                    2    0.0
26919   2023-04-20 13:27:58.952  emobility:69636                    2    0.0
32712   2023-04-20 17:27:40.697  emobility:69636                    0    2.0
35297   2023-04-20 17:48:41.533  emobility:69636                    0    0.0
42369   2023-04-21 06:10:26.457  emobility:69636                    2    0.0
42370   2023-04-21 08:35:26.773  emobility:69636                    2    0.0
48497   2023-04-21 09:12:49.563  emobility:69636                    1    1.0
54526   2023-04-21 10:38:58.442  emobility:69636                    2    0.0
60652   2023-04-21 11:31:54.043  emobility:69636                    2    0.0
66726   2023-04-21 12:09:40.481  emobility:69636                    1    1.0
72852   2023-04-21 13:17:56.915  emobility:69636                    1    0.0
78978   2023-04-21 18:33:06.638  emobility:69636                    1    0.0
85030   2023-04-22 09:00:03.002  emobility:69636                    1    0.0
91161   2023-04-22 09:15:35.518  emobility:69636                    1    0.0
97289   2023-04-22 09:46:14.932  emobility:69636                    1    0.0
103420  2023-04-22 11:14:29.529  emobility:69636                    1    0.0
109424  2023-04-22 11:48:56.172  emobility:69636                    0    1.0
115546  2023-04-22 12:22:59.355  emobility:69636                    0    0.0
121669  2023-04-22 12:56:53.333  emobility:69636                    1    0.0
127791  2023-04-22 13:30:56.516  emobility:69636                    1    0.0
129265  2023-04-22 14:12:21.960  emobility:69636                    0    1.0
135230  2023-04-22 14:45:02.352  emobility:69636                    0    0.0
141360  2023-04-22 15:27:15.208  emobility:69636                    0    0.0
147491  2023-04-22 15:57:23.152  emobility:69636                    0    0.0
153620  2023-04-22 17:15:46.375  emobility:69636                    0    0.0
159751  2023-04-23 08:21:41.872  emobility:69636                    1    0.0
165730  2023-04-23 09:29:35.465  emobility:69636                    1    0.0
171861  2023-04-23 10:15:29.551  emobility:69636                    1    0.0
177990  2023-04-23 12:34:13.682  emobility:69636                    0    1.0
184122  2023-04-23 14:57:02.414  emobility:69636                    0    0.0
189202  2023-04-24 07:41:40.360  emobility:69636                    0    0.0
195338  2023-04-24 08:28:13.740  emobility:69636                    1    0.0
201475  2023-04-24 08:59:03.478  emobility:69636                    2    0.0
207301  2023-04-24 14:30:32.975  emobility:69636                    2    0.0
210801  2023-04-25 17:35:52.924  emobility:69636                    2    0.0
216901  2023-04-25 18:23:29.045  emobility:69636                    2    0.0
223001  2023-04-25 18:54:24.756  emobility:69636                    2    0.0
229101  2023-04-25 19:11:58.139  emobility:69636                    2    0.0

In [66]:
def shift_with_latter(available):
    shift = (available.shift() - available).cumsum()
    return shift

def difference_with_latter(available:np.array):
    difference = (available.diff()).cumsum()
    return difference

# Group the data frame by range_identifier and aggregate the variables
new_df = data.groupby(['station_id', 'load']).agg(            
    usage=pd.NamedAgg(column='num_bikes_available', aggfunc=difference_with_latter))
    
new_df.head()

   # (df[cond_col_name].shift() != df[cond_col_name])

                                      usage
station_id   load
2em_cars:100 2023-04-19 14:32:32.048    NaN
             2023-04-20 09:35:40.112    NaN
             2023-04-20 11:09:42.013    NaN
             2023-04-20 12:24:18.640    NaN
             2023-04-20 13:39:38.737    NaN

In [39]:
new_df.head()

                                         usage
load                    station_id
2023-04-19 14:21:41.445 emobility:69636    NaN
                        emobility:69644    NaN
                        emobility:69652    NaN
                        emobility:69677    NaN
                        emobility:69682    NaN

In [27]:
# group by load and station_id
#data_group = data[data['station_id']=='emobility:69636'].groupby('load').size().reset_index(name='count').sort_values(by=['load'])
data_group = data.groupby(['load', 'station_id']).size().reset_index(name='count').sort_values(by=['station_id']).sort_values(by=['load'])
data_group = data_group.groupby('station_id')
data_group.get_group('emobility:69636')

                           load       station_id  count
0       2023-04-19 14:21:41.445  emobility:69636      1
6100    2023-04-19 19:09:32.167  emobility:69636      1
8600    2023-04-20 09:24:48.047  emobility:69636      1
14700   2023-04-20 10:58:48.597  emobility:69636      1
20800   2023-04-20 12:13:30.749  emobility:69636      1
26900   2023-04-20 13:27:58.952  emobility:69636      1
32600   2023-04-20 17:27:40.697  emobility:69636      1
35200   2023-04-20 17:48:41.533  emobility:69636      1
42300   2023-04-21 06:10:26.457  emobility:69636      1
42301   2023-04-21 08:35:26.773  emobility:69636      1
48401   2023-04-21 09:12:49.563  emobility:69636      1
54501   2023-04-21 10:38:58.442  emobility:69636      1
60601   2023-04-21 11:31:54.043  emobility:69636      1
66701   2023-04-21 12:09:40.481  emobility:69636      1
72801   2023-04-21 13:17:56.915  emobility:69636      1
78901   2023-04-21 18:33:06.638  emobility:69636      1
85001   2023-04-22 09:00:03.002  emobility:69636      1
91101   2023-04-22 09:15:35.518  emobility:69636      1
97201   2023-04-22 09:46:14.932  emobility:69636      1
103301  2023-04-22 11:14:29.529  emobility:69636      1
109401  2023-04-22 11:48:56.172  emobility:69636      1
115501  2023-04-22 12:22:59.355  emobility:69636      1
121601  2023-04-22 12:56:53.333  emobility:69636      1
127701  2023-04-22 13:30:56.516  emobility:69636      1
129101  2023-04-22 14:12:21.960  emobility:69636      1
135201  2023-04-22 14:45:02.352  emobility:69636      1
141301  2023-04-22 15:27:15.208  emobility:69636      1
147401  2023-04-22 15:57:23.152  emobility:69636      1
153501  2023-04-22 17:15:46.375  emobility:69636      1
159601  2023-04-23 08:21:41.872  emobility:69636      1
165701  2023-04-23 09:29:35.465  emobility:69636      1
171801  2023-04-23 10:15:29.551  emobility:69636      1
177901  2023-04-23 12:34:13.682  emobility:69636      1
184001  2023-04-23 14:57:02.414  emobility:69636      1
189001  2023-04-24 07:41:40.360  emobility:69636      1
195101  2023-04-24 08:28:13.740  emobility:69636      1
201201  2023-04-24 08:59:03.478  emobility:69636      1
207301  2023-04-24 14:30:32.975  emobility:69636      1
210801  2023-04-25 17:35:52.924  emobility:69636      1
216901  2023-04-25 18:23:29.045  emobility:69636      1
223001  2023-04-25 18:54:24.756  emobility:69636      1
229101  2023-04-25 19:11:58.139  emobility:69636      1

In [ ]:
(df[cond_col_name].shift() != df[cond_col_name])

In [12]:
data_group = data.groupby(['station_id', 'load']).size().reset_index(name='count')
data_group

            station_id                     load  count
0         2em_cars:100  2023-04-19 14:32:32.048      1
1         2em_cars:100  2023-04-20 09:35:40.112      1
2         2em_cars:100  2023-04-20 11:09:42.013      1
3         2em_cars:100  2023-04-20 12:24:18.640      1
4         2em_cars:100  2023-04-20 13:39:38.737      1
...                ...                      ...    ...
233096  sponticar:null  2023-04-24 08:42:28.917      1
233097  sponticar:null  2023-04-24 09:13:20.516      1
233098  sponticar:null  2023-04-25 17:50:18.122      1
233099  sponticar:null  2023-04-25 18:37:59.999      1
233100  sponticar:null  2023-04-25 19:10:51.686      1

[233101 rows x 3 columns]